package com.cowork.app;

import com.getcapacitor.BridgeActivity;

/**
 * MainActivity class.
 * Core Android application entry activity generated by Capacitor.
 * Extends BridgeActivity to load the web asset runtime interface and plugins.
 */
public class MainActivity extends BridgeActivity {}
